---
title: Adraclub Holiday Homes Jekyll Theme
timezone: UTC
collections:
  changelog:
    title: Changelog
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  changelog:
    output: false
description: A Blog Theme by Statix Design
email: your-email@example.com
author: Statix Design
url: http://adraclub.github.io
twitter_username: adraclub
github_username: adraclub
facebook_username: adraclub
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
- jekyll-feed
- jekyll-include-cache
- jekyll-paginate
- jekyll-redirect-from
- jekyll-tidy
- jekyll-toc
- jekyll-random
theme-plugins:
  charts-c3:
    name: c3.js Charts
    files:
    - css
    - js
  maps-google:
    name: Google Maps
    files:
    - css
    - js
  input-mask:
    name: Input Mask
    files:
    - js
  datatables:
    name: Datatables
    files:
    - js
exclude:
<<<<<<< HEAD
  - package.json
  - gulpfile.js
=======
- package.json
- gulpfile.js
>>>>>>> 6e22079fa996c2cc1e500a113bdac6465c5c5741
