title:             Adra Club Apart Tatil Evleri
description:       A Blog Theme by Statix Design
email:             your-email@example.com
author:            Statix Design
url:               "http://adraclub.github.io"

# Social Profiles
twitter_username:  adraclub
github_username:   adraclub
facebook_username: adraclub

# Build settings
markdown:          kramdown
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-tidy
  - jekyll-toc
  - jekyll-random

exclude:
  - package.json
  - gulpfile.js

collections:
  changelog:
    output: false
  servisler:
    output: false
