title:             Ören Adra Club Apart Tatil Evleri
description:       Ailenizle Birlikte Harika Bir Tatil
email:             bilgi@adraclub.com
author:            Statix Design
url:               "http://adraclub.github.io"

# Social Profiles
facebook_username: orenadraclubapart
instagram_username: orenadraclubtatil

# Build settings
markdown:          kramdown
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-tidy

exclude:
  - package.json
  - gulpfile.js

collections:
  changelog:
    output: false
  servisler:
    output: false
