title:             Statix Hotel Jekyll Theme
description:       A Hotel Theme by Statix Design
email:             admin@statixdesign.com
author:
   name: Statix Design
   url: https://statixdesign.com
baseurl:           "/"
url:               "http://adraclub.github.io"

# Social Profiles
twitter_username:  adraclub
github_username:   adraclub
facebook_username: adraclub

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-tidy

sass:
  style: compressed


