# These rules will change if you change your site’s custom domains or HTTPS settings

# Redirect default Netlify subdomain to primary domain
https://adraclub.netlify.com/*  https://www.adraclub.com/:splat 301!